# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 11e685b
_src_path: https://gitlab.com/gemseo/dev/copier-gemseo
author_email: contact@gemseo.org
author_name: GEMSEO developers
gemseo_min_version: '6'
package_is_a_gemseo_plugin: true
project_is_open_source: true
project_name: gemseo-pymoo
project_name_suffix: pymoo
project_slug: gemseo_pymoo
short_description: A GEMSEO wrapper for pymoo optimization algorithms.
use_gemseo_develop: true
