include:
  - project: "gemseo/dev/ci-includes"
    file: "plugin.yml"

test:
  parallel:
    matrix:
      - TAG:
          - docker
          - windows-server-2012
        TOX_ENV_NAME:
          - py37-coverage
          - py38-coverage
          - py39-coverage
